### ISSUE TITLE
AzureAD auth issues

### ISSUE THREAD

**Issue by shiva252** [hashicorp/vault-plugin-auth-azure#24]
Hi there,

Not sure if I was supposed to post it here or the main vault repo...but I'm trying to set up AzureAD Authenticating to Azure using a Service Principal and a Client Secret:

While executing the "vault write auth/azure/login" i am getting below error. 

For testing purpose i am executing  the vault login command from the same k8n pod where vault is installed.

Error writing data to auth/azure/login: Error making API request.

URL: PUT http://*******:8200/v1/auth/azure/login
Code: 500. Errors:

* vm client did not return identity information

**Comment by austingebauer** [comment]
@shiva252 - My apologies for how long it took to get a reply on this issue. I'm familiar with Vault's Azure auth method and would be happy to help if you still need it 😄 Please let me know. Thanks!

**Comment by austingebauer** [comment]
I'm going to close this issue for now. _Please_ feel free to reopen it if you have any questions or still need help with this 🙂
