### ISSUE TITLE
"SubscriptionNotFound" error when client tries to authenticate in Azure Gov

### ISSUE THREAD

**Issue by null-route** [hashicorp/vault-plugin-auth-azure#26]
Hi all,

After a day of troubleshooting I still haven't been able to make any progress on this and I'm beginning to think it may not be a simple misconfiguration. Is anyone successfully using the Vault Azure authentication backend in Azure Gov? Here is my current configuration (Vault servers are running 1.2.3):

- An application registration has been created, per https://www.vaultproject.io/docs/auth/azure.html#prerequisites-, and given the documented vm/vmss read permissions.
- An Azure auth backend has been configured within Vault and provided with the application registration client_id and client_secret that were created previously. Config snippet:
```
[server]$ vault read /auth/azure/config
Key            Value
---            -----
client_id      $vault_app_reg_client_id
environment    AzureUSGovernmentCloud
resource       https://management.usgovcloudapi.net/
tenant_id      $tenant_id
```
When an Azure Gov client VM attempts to authenticate using this authentication backend, they receive the following error (request parameters included):
```
[client]$ curl --request POST --data '{"role": "$CLIENT_ROLE", "jwt": "$CLIENT_ACCESS_TOKEN", "resource_group_name": "$CLIENT_RG", "vm_name": "$CLIENT_VM_NAME", "subscription_id": "$CLIENT_SUBID"}' https://$VAULT_IP:8200/v1/auth/azure/login -s | jq
{
  "errors": [
    "unable to retrieve virtual machine metadata: compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription '$CLIENT_SUBID' could not be found.\""
  ]
}
```

However, the Vault application registration credentials that were loaded in the backend can both read subscriptions and VMs, so they have the required permissions. The following commands can be used to demonstrate:
```
[server]$ export ACCESS_TOKEN="$(curl -X POST -d 'grant_type=client_credentials&client_id=$VAULT_CLIENT_ID&client_secret=$VAULT_CLIENT_SECRET&resource=https://management.usgovcloudapi.net/' https://login.microsoftonline.com/$TENANT_ID/oauth2/token -s | jq -r '.access_token')"
[server]$ curl -X GET -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" https://management.usgovcloudapi.net/subscriptions?api-version=2019-03-01 -s | jq
[server]$ curl -X GET -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" https://management.usgovcloudapi.net/subscriptions/$CLIENT_SUBID/providers/Microsoft.Compute/virtualMachines?api-version=2019-03-01 -s | jq
```

My theory is that something in the backend isn't utilizing the correct Azure Gov API endpoints when environment is set to `AzureUSGovernmentCloud`, but I haven't found an obvious error during my initial read through the source. Any ideas?

**Comment by thardie** [comment]
I've done a tcpdump from when the affected request is sent. The SNI in the request vault makes definitely has "management.azure.com" in it and NOT "management.usgovcloudapi.net". I believe this is actually a bug in Azure/go-autorest
